const softSkills = [
  'Adaptability',
  'Attention To Detail',
  'Communication',
  'Communicator',
  'Communicators',
  'Conflict Management',
  'Conflict Resolution',
  'Critical Thinking',
  'Critical Thinker',
  'Customer Service',
  'Emotional Intelligence',
  'English working',
  'Experience',
  'Fast Paced',
  'Fast-Paced',
  'Fluent English',
  'Fluent In English',
  'Innovative',
  'independent',
  'independently',
  'Interpersonal Skills',
  'Leadership',
  'Microservices',
  'Organizational Skills',
  'Passion',
  'Passionate',
  'Positive Attitude',
  'Presentation Skills',
  'Professionalism',
  'Problem Solver',
  'Problem Solving',
  'Problem-Solving',
  'Team player',
  'Team players',
  'Team Work',
  'Team work',
  'Teamwork',
  'Time Management',
  'Work Ethic',
];

const hardSkills = [
  '.NET',
  'ASP .NET',
  'API',
  'AWS',
  'Artificial Intelligence',
  'Asynchronous',
  'Asynchronous Programming',
  'Angular',
  'AngularJS',
  'Bootstrap',
  'C\\+\\+',
  'CSS',
  'CSS3',
  'Cloud',
  'Cloud Computing',
  'Components',
  'Cross Browser',
  'Cross Browser Compatibility',
  'Cyber security',
  'Cybersecurity',
  'Data Science',
  'Deploy',
  'Design',
  'Docker',
  'ES6',
  'ES7',
  'Express',
  'Express.js',
  'Expressjs',
  'Firebase',
  'Front End',
  'Front-End',
  'FrontEnd',
  'Full Stack',
  'Full-Stack',
  'FullStack',
  'Game Development',
  'Git',
  'High Traffic',
  'Hooks',
  'HTML',
  'HTML5',
  'Java',
  'JavaScript',
  'JS',
  'Kubernetes',
  'Machine Learning',
  'Mobile Development',
  'Modules',
  'MongoDB',
  'Networking',
  'NoSQL',
  'Node',
  'Node JS',
  'Node.js',
  'NodeJS',
  'Performance',
  'Project Management',
  'Python',
  'React',
  'React Hooks',
  'Reactjs',
  'Redux',
  'Responsive Design',
  'Restful API',
  'SAAS',
  'Scalability',
  'SEO',
  'SEO Best Practices',
  'SQL',
  'Test',
  'Vue',
  'Vuejs',
  'Web Application',
  'Web Applications',
  'Web Development',
  'Webpack',
];

module.exports = {
  softSkills,
  hardSkills,
};
